#!/bin/bash -xe
containers=$(find * -maxdepth 0 -type d)

keep_alive() {
	if [[ $(docker-compose ps -q | xargs docker inspect -f '{{ .State.ExitCode }}' | grep -v 0 | wc -l | tr -d ' ') -ne 0 ]]; then
		echo "A container has exited. Restarting docker stack"
		docker-compose down
		docker-compose up &
	fi
}

mount -o bind /data /var/lib/docker

# Start docker and services
if ! docker info &>/dev/null; then
	wrapdocker echo
fi

for i in $containers; do
	docker-compose build $i
done
docker rm -v $(docker ps -a -q -f status=exited 2>/dev/null) &>/dev/null || :
docker rmi $(docker images -f "dangling=true" -q 2>/dev/null) &>/dev/null || :
docker-compose down || :
docker-compose up &

set +x
while true; do
	sleep 10m
	keep_alive
done
docker-compose ps | tail -n+3 | grep -v Up | wc -l